### PR TITLE
thumbnail generation fix and scale

### PR DESCRIPTION
**Pull request by camjac251**
ffmpeg can sometimes generate broken thumbnails (sometimes a full grey image) when it seeks in the input instead of the output. When it's added after the input, it is a bit slower but it is more stable and will fixes the issue for various formats like HEVC or Prores.

The resolution could benefit from being increased 3x for users who scale up the webpage in their browser or tablet views. It becomes scaled up 200% or 300% when viewed on a smaller screen.

### CODE REVIEW

**Comment by camjac251** [comment]
I would like to propose also that thumbnails could be webp files instead of PNGs.
This is the what I currently have
`ffmpeg -hwaccel auto -i preview-original.mov -ss 29 -vframes 1 -vf scale=600:600:force_original_aspect_ratio=decrease -pix_fmt yuv420p -c:v libwebp -quality 99 ok.webp`

On one test, the generated png was `333KB` while the webp image was `47KB`

**Comment by BobbyWibowo** [comment]
Not much of a fan of WEBP unless clients are properly detected from server-side (only serve them on clients that support them).
I'd recommend something like PageSpeed if you really need to. It has automatic rewrite to WEBP and only for clients that support them.

**Comment by BobbyWibowo** [comment]
Doubtful about the use of 2x or 3x of thumbnails as well. They're thumbnails after all. Their sole purpose is only to get rough immediate information of what the file is about.

I'm interested about the grey image issue however. I've never really had that on my safe iirc.

**Comment by camjac251** [comment]
Could the thumbnail size become a config variable? This would allow flexibility in the user's choice.

**Comment by BobbyWibowo** [comment]
That's an option. Want to make a PR for that or should I do it?

**Comment by camjac251** [comment]
I wouldn't know how to. It would take me a little while to figure out how. I don't mind taking the time if it's easier for you.

**Comment by camjac251** [comment]
Would it be something like this?
```node
await new Promise((resolve, reject) => {
  ffmpeg(input)
    .inputOptions([
    ])
    .output(thumbname)
    .outputOptions([
      `-ss ${duration * 20 / 100}`,
      '-vframes 1',
      '-vf scale=(config.uploads.generateThumbs.size):(config.uploads.generateThumbs.size):force_original_aspect_ratio=decrease'
    ])
```

**Comment by BobbyWibowo** [comment]
```js
`-vf scale=${config.uploads.generateThumbs.size}:${config.uploads.generateThumbs.size}:force_original_aspect_ratio=decrease`
```
Don't forget the one for images above that (less troublesome than this one to change).

Also if it was me, I'd add a fallback logic at the very top of the file (e.g. when the key is missing from config, fallback to `200`).

**Comment by camjac251** [comment]
I didn't know which part to the add fallback key to.

**Comment by BobbyWibowo** [comment]
I guess add a `thumbSize` var or something before these lines:
https://github.com/BobbyWibowo/lolisafe/blob/776414814dd990914abe289c01f1f2a43709482a/controllers/utilsController.js#L28-L31
which points to the config OR fallback value, then use that new var instead (`self.thumbSize`).\
Look at `clamd` object above those for examples.

Also
> Don't forget the one for images above that

**Comment by camjac251** [comment]
If `thumbSize` is added at the top, wouldn't the variables at the bottom need to be `self.thumbSize`?

Also I thought I added the code in the right spot for images
https://github.com/BobbyWibowo/lolisafe/blob/9a4c0d5cea3d2b515f343b696efb4e32be3f0ed4/controllers/utilsController.js#L225-L226

**Comment by BobbyWibowo** [comment]
> Also I thought I added the code in the right spot for images

lmao ngl i missed them

> If thumbSize is added at the top, wouldn't the variables at the bottom need to be self.thumbSize?

Yeah, but that's fine. It's mostly to expose the var to the rest of the infrastructure (e.g. can be accessed with `utils.thumbSize` from `uploadsController.js`). Not really used atm, but less codes to change when you do need to use it in the future.

**Comment by camjac251** [comment]
Is this ready for merging?

**Comment by BobbyWibowo** [comment]
> If thumbSize is added at the top, wouldn't the variables at the bottom need to be self.thumbSize?

You haven't changed these tho

**Comment by camjac251** [comment]
I thought you said it was fine to ignore it earlier?


> Yeah, but that's fine. It's mostly to expose the var to the rest of the infrastructure (e.g. can be accessed with `utils.thumbSize` from `uploadsController.js`). Not really used atm, but less codes to change when you do need to use it in the future.

**Comment by BobbyWibowo** [comment]
I thought you were questioning the necessity of it

**Comment by camjac251** [comment]
Is this how it should look?

**Comment by BobbyWibowo** [comment]
Looks perfect

Still not sure about using output option over the current input option though
Can you at least send some sample files that are confirmed to have that issue if using input option?

I usually build ffmpeg from their git source for my PC, so it's often up to date indeed,
but my server uses a pretty old copy anyway (ffmpeg 2.8.15 from somewhen in 2018), yet I don't recall seeing any files getting this issue

**Comment by camjac251** [comment]
I'm update to date too on the development branch. I could send you this file if you wanted to test it yourself as well. It's more a limit with the implementation. Seeing before the input is not frame accurate so it's faster but can lead to corrupt frames. Seeking after is slower but you can reliably get the first frame.

This is my result https://imgsli.com/MTc0NjA

**Comment by camjac251** [comment]
https://stackoverflow.com/a/47110453 might shed some light on it.

**Comment by BobbyWibowo** [comment]
Just send me the file I guess. Even after reading the SO, so far I'm still in the opinion that this issue seems too specific to be worth the performance costs.
Like, of course I don't mind which method you use in the end with your own installation, but I'm unable to simply accept that into the codebase, if you get what I mean.

**Comment by camjac251** [comment]
Could we compromise and allow a config option for input and output options. Since the file is over 512MB I can't upload it to your safe. Here is the file on my server https://a.uploadi.moe/mq7.m2ts
And what I tried seeking to 
`ffmpeg -i File.m2ts -ss 00:00:38 -vframes 1 working.png`
`ffmpeg -ss 00:00:38 -i File.m2ts -vframes 1 broken.png`

**Comment by BobbyWibowo** [comment]
Base this on https://github.com/BobbyWibowo/lolisafe/commit/28c64d531a36a110a3069d71c51bba87a4b9a0fc and get rid of the input->ouput option stuff.
That commit should work with the video file you mentioned, while being a lot faster than output option still.
Sample thumb: https://i.fiery.me/private/out.png

**Comment by BobbyWibowo** [comment]
Oh wait never mind, I'll work on this as-is

**Comment by camjac251** [comment]
I don't know if I did it right 😟

**Comment by BobbyWibowo** [comment]
Unfortunately you did miss a few syntax errors, even on the state that I claimed to look perfect (I didn't check very carefully either, lmao).
e.g.
```
        width: ${self.thumbSize},
        height: ${self.thumbSize},
```
wrapping the variables within `${...}` was only necessary in [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) (i.e. the line for ffmpeg options), so those 2 lines weren't correct.

Either way I ended up merging up to commit cf2593465af785c4e37969e71724d00050e73ef2 instead.

**Pull request closed without merging**
